apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-html
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: test-html
          image: docker.io/kiyo37/test-html:latest
