apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-html
  template:
    metadata:
      labels:
        app: test-html
    spec:
      containers:
        - name: test-html
          image: docker.io/kiyo37/test-html:latest  # patch で上書き予定
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-html
spec:
  selector:
    app: test-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
